version: '3.4'

services:

  back: 
    container_name : "backend"
    build: ./backend
    
    ports:
      - 5000:5000
    expose: 
      - 5000  

  front:
    container_name: "frontend"
    build: ./frontend
    depends_on: 
        - back
    ports:
      - 3000:3000   
    expose: 
      - 3000
    
      